spring.application.name=subscription-service
server.port=${PORT:8080}

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/subscription_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# SQL Logging
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

# Scheduler Timezone
spring.task.scheduling.time-zone=Asia/Kolkata

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}